"use strict";
const pool = require('../models/db');

/** race entity:
 * id : bigint
 * title : text
 * distance : string 
 *          from choices [marathon, half marathon, 10km, 
 *          5km, 1mi, fun run, ultramarathon 
 *          (42.2km+/26.2mi+), other]
 * description : text
 * authorID : id of author
 * date : timestamp
 */

async function checkTable(){
    const queryText = "CREATE TABLE IF NOT EXISTS races ( id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, title text NOT NULL, distance int NOT NULL, description text, authorID bigint, date TIMESTAMP NOT NULL);";
    const result = await pool.query(queryText);
}

async function addRace(title, distance, description, authorID) {
    let queryText = "INSERT INTO races (title, distance, description, authorID) VALUES ($1, $2, $3, $4) RETURNING *";
    let values = [title, distance, description, authorID];
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

async function deleteRace(id) {
    let queryText = "DELETE FROM races WHERE id = $1 ";
    const values = [id];
    const result = await pool.query(queryText, values);
    return result.rowCount;
}

async function getAllRaces() {
    const queryText = "SELECT * FROM races";

    const result = await pool.query(queryText);
    return result.rows;
}

async function getRaceById(id) {
    const queryText = "SELECT * FROM races where id= $1";
    const values = [id];
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

async function searchRaces(title, distance, username){
    /** approach : 
     * search by username involves a join and matching u.username
     * we check for notnull parameters, than append a matching
     * boolean to the query text
     * use paramcount to add $1, $2, $X to the query text,
     * like in other methods */

    let queryText = "SELECT r.*, u.username FROM races r JOIN users u ON r.authorID = u.id WHERE 1=1";
    let values = [];
    let paramCount = 0
    if (title){
        queryText += ` AND r.title ILIKE $${++paramCount}`;
        values.push(`%${title}%`);
    }
    if (distance){
        queryText += ` AND r.distance LIKE $${++paramCount}`;
        values.push(distance);
    }
    if (username){
        queryText += ` AND u.username ILIKE $${++paramCount}`;
        values.push(`%${username}%`);
    }

    const result = await pool.query(queryText, values);
    return result.rows;
}


module.exports = {
    getAllRaces,
    getRaceById,
    deleteRace,
    addRace
};
