"use strict";
const pool = require('../models/db');

/** race entity:
 * id : bigint
 * title : text
 * distance : string 
 *          from choices [marathon, half marathon, 10km, 
 *          5km, 1mi, fun run, ultramarathon 
 *          (42.2km+/26.2mi+), other]
 * description : text
 * authorID : id of author
 * raceimage : text
 * date : timestamp
 */

async function checkTable(){
    const queryText1 = "CREATE TABLE IF NOT EXISTS races (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, title TEXT NOT NULL, distance TEXT NOT NULL, description TEXT, authorID BIGINT, raceimage TEXT, date TIMESTAMP NOT NULL, FOREIGN KEY (authorID) REFERENCES users(id) ON DELETE CASCADE);";
    await pool.query(queryText1);
    const queryText2 = "CREATE TABLE IF NOT EXISTS race_participant (raceid BIGINT NOT NULL, userid BIGINT NOT NULL, PRIMARY KEY (raceid, userid), FOREIGN KEY (raceid) REFERENCES races(id) ON DELETE CASCADE, FOREIGN KEY (userid) REFERENCES users(id) ON DELETE CASCADE);";
    await pool.query(queryText2);
    return;
}

async function addRace(title, distance, description, authorID, date) {
    let queryText = "INSERT INTO races (title, distance, description, authorID, date) VALUES ($1, $2, $3, $4, $5) RETURNING *";
    let values = [title, distance, description, authorID, date];
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

async function updateRace(id, title, distance, description, authorID, date) {
    let queryText = "UPDATE races SET title = $1, distance = $2, description = $3, authorID = $4, date = $5 WHERE id = $6 RETURNING *";
    const values = [title, distance, description, authorID, date, id];
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

async function updateRaceImage(id, raceimage) {
    let queryText = "UPDATE races SET raceimage = $1 WHERE id = $2 RETURNING *";
    const values = [raceimage, id];
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

async function deleteRace(id) {
    let queryText = "DELETE FROM races WHERE id = $1 ";
    const values = [id];
    const result = await pool.query(queryText, values);
    return result.rowCount;
}

async function getAllRaces() {
    checkTable();
    const queryText = "SELECT * FROM races";
    const result = await pool.query(queryText);
    return result.rows;
}

async function getRaceById(id) {
    const queryText = "SELECT * FROM races where id= $1";
    const values = [id];
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

async function searchRaces(title, distance, username){
    /** approach : 
     * search by username involves a join and matching u.username
     * we check for notnull parameters, than append a matching
     * boolean to the query text
     * use paramcount to add $1, $2, $X to the query text,
     * like in other methods */

    let queryText = "SELECT r.*, u.username FROM races r JOIN users u ON r.authorID = u.id WHERE 1=1";
    let values = [];
    let paramCount = 0
    if (title){
        queryText += ` AND r.title ILIKE $${++paramCount}`;
        values.push(`%${title}%`);
    }
    if (distance){
        queryText += ` AND r.distance LIKE $${++paramCount}`;
        values.push(distance);
    }
    if (username){
        queryText += ` AND u.username ILIKE $${++paramCount}`;
        values.push(`%${username}%`);
    }

    const result = await pool.query(queryText, values);
    return result.rows;
}

async function getRacesByAuthor(authorID){
    const queryText = "SELECT * FROM races WHERE authorID = $1";
    const values = [authorID];
    const result = await pool.query(queryText, values);
    return result.rows;
}

async function getRacesForProfile(authorid){
    const queryText = "SELECT * FROM races WHERE authorID = $1 LIMIT 3";
    const values = [authorid];
    const result = await pool.query(queryText, values);
    return result.rows;
}

async function addParticipant(raceID, userID){
    const queryText = "INSERT INTO race_participant (raceid, userid) VALUES ($1, $2) RETURNING *";
    const values = [raceID, userID];
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

async function removeParticipant(raceID, userID){
    const queryText = "DELETE FROM race_participant WHERE raceid = $1 AND userid = $2 RETURNING *";
    const values = [raceID, userID];
    const result = await pool.query(queryText, values);
    return true;
}

async function checkParticipant(raceID, userID){
    const queryText = "SELECT * FROM race_participant WHERE raceid = $1 AND userid = $2";
    const values = [raceID, userID];
    const result = await pool.query(queryText, values);
    if (result.rows.length > 0){
        return true;
    }
    return false;
}

async function getParticipants(raceid){
    const queryText = "SELECT u.username, u.id FROM race_participant r join users u on r.userid = u.id WHERE raceid = $1";
    const values = [raceid];
    const result = await pool.query(queryText, values);
    if (result.rowCount < 1){
        return null;
    }
    return result.rows;
}


module.exports = {
    getAllRaces,
    getRaceById,
    deleteRace,
    addRace,
    updateRace,
    updateRaceImage,
    getRacesByAuthor,
    getRacesForProfile,
    searchRaces,
    addParticipant,
    removeParticipant,
    checkParticipant,
    getParticipants
};
