const pool = require('../models/db');
const bcrypt = require('bcrypt');

/** user entity:
 * id : bigint
 * username : text
 * password : text (hashed with bcrypt)
 * bio : text
 * creationDate : timestamp
 * role : text (default user)
 * favdist : text
 * shoes : text
 * profileImage : text
 */

async function checkTable(){
    const queryText = "CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, username TEXT NOT NULL UNIQUE, password TEXT NOT NULL, bio TEXT, creationDate TIMESTAMP NOT NULL DEFAULT NOW(), role TEXT DEFAULT 'user', favDist TEXT, shoes TEXT, profileImage TEXT);"
    await pool.query(queryText);

    await pool.query("ALTER TABLE users ADD COLUMN IF NOT EXISTS profileImage TEXT;");
}

checkTable();

async function getAllUsers() {
    const queryText = "SELECT * FROM users";
    const result = await pool.query(queryText);
    return result.rows;
}

async function getUserById(id) {
    const queryText = "SELECT * FROM users where id= $1";
    const values = [id];
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

async function getUserByUsername(username) {
    const queryText = "SELECT * FROM users where username= $1";
    const values = [username];
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

async function deleteUser(id) {
    let queryText = "DELETE FROM users WHERE id =$1; ";
    const values = [id];
    const result = await pool.query(queryText, values);
    return result.rowCount;
}

async function addUser(username, password) {
    const defaultBio = "Hello, I'm new to Feet First.";
    let queryText = "INSERT INTO users ( username, bio, password) VALUES ($1, $2, $3) RETURNING *";
    let values = [username, defaultBio, password];
    const result = await pool.query(queryText, values);

    // return the new user
    return result.rows[0];
}

async function verifyPassword(password, hashedPass){
    return await bcrypt.compare(password, hashedPass);
}

async function updateProfileImage(userId, imagePath) {
    const queryText = "UPDATE users SET profileImage = $1 WHERE id = $2 RETURNING *";
    const result = await pool.query(queryText, [imagePath, userId]);
    return result.rows[0];
}

async function updateUser(userId, bio, favDist, shoes, profileImage) {
    let updates = [];
    let values = [];
    let paramCount = 0;

    // check if the parameters are being updated (or there's no change)
    
    if (bio) {
        updates.push(`bio = $${++paramCount}`);
        values.push(bio);
    }
    if (favDist) {
        updates.push(`favdist = $${++paramCount}`);
        values.push(favDist);
    }
    if (shoes) {
        updates.push(`shoes = $${++paramCount}`);
        values.push(shoes);
    }
    if (profileImage) {
        updates.push(`profileImage = $${++paramCount}`);
        values.push(profileImage);
    }
    
    if (updates.length === 0) {
        // no updates made, so return the user anyways
        return await getUserById(userId);
    }
    
    let queryText = `UPDATE users SET ${updates.join(', ')} WHERE id = $${++paramCount} RETURNING *`;
    values.push(userId);
    
    const result = await pool.query(queryText, values);
    return result.rows[0];
}

module.exports = {
    checkTable,
    getAllUsers,
    getUserById,
    getUserByUsername,
    deleteUser,
    addUser,
    verifyPassword,
    updateProfileImage,
    updateUser
};